version: '3.7'
services:
  server:
    build:
      context: ./server
    restart: always
    extra_hosts:
      - "owner:172.17.0.1"
    ports:
      - 5000:5000
    volumes:
      - /home/igor/Nadya/onlines:/usr/src/app/onlines

